### ISSUE TITLE
Package request: mpv with video

### ISSUE THREAD

**Issue by Neo-Oli** [xeffyr/termux-extra-packages#14]
mpv in termux can only do audio. It would be cool to have it also do video in termux-x-packages.

**Comment by xeffyr** [comment]
Package added as `mpv-x`.
However, it won't work on Nexus 7 (Android 5.1.1) but working on my other devices and i686 AVD image (Android 8.0). Video output a bit laggy but sound seems ok.

**Comment by Neo-Oli** [comment]
cool. thanks a lot. 

Yes it's quite choppy. I knew it was going to be slow over ssh, but I was hoping it would at least be fast in the SDL X Server app. 
But it at least allows me to check the content of a video file from my Library, before I open it another way.
