### ISSUE TITLE
Package Request: pandoc (official binary)

### ISSUE THREAD

**Issue by amuramatsu** [xeffyr/termux-extra-packages#21]
[pandoc](https://pandoc.org) is the most famous document converter.

No one succeed to compile it for termux, but I found official binary of pandoc can run on qemu-user-x86_64 in your repository.

Ofcourse, pandoc on qemu is very slow, but better than nothing.  I think packaging of pandoc binary is useful for many people.

**Comment by xeffyr** [comment]
I will add it, but network related stuff (converting online web pages) will not be available.

**Comment by xeffyr** [comment]
Added in https://github.com/xeffyr/termux-extra-packages/commit/22fccfa919524f0319f18d791683eed49df1c1a5.
