### ISSUE TITLE
apt update issue

### ISSUE THREAD

**Issue by darktrue9** [xeffyr/termux-extra-packages#24]
$ apt update
Ign:1 https://xeffyr.github.io/termux-x-repository termux InRelease
Err:2 https://xeffyr.github.io/termux-x-repository termux Release
  404  Not Found
Hit:3 https://termux.net stable InRelease
Reading package lists... Done
E: The repository 'https://xeffyr.github.io/termux-x-repository termux Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
$ pkg update
Ign:1 https://xeffyr.github.io/termux-x-repository termux InRelease
Err:2 https://xeffyr.github.io/termux-x-repository termux Release
  404  Not Found
Hit:3 https://termux.net stable InRelease
Reading package lists... Done
E: The repository 'https://xeffyr.github.io/termux-x-repository termux Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
$

**Comment by xeffyr** [comment]
Soluting here: https://github.com/xeffyr/termux-extra-packages#how-to-enable-extra-packages-in-termux

https://xeffyr.github.io/termux-x-repository - this url is no longer exists.
