### ISSUE TITLE
mpv CANNOT LINK EXECUTABLE

### ISSUE THREAD

**Issue by Neo-Oli** [xeffyr/termux-extra-packages#27]
```
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/libexec/mpv": library "libdrm.so" not found
```
It seems mpv-x is missing libdrm as a dependency.

**Comment by xeffyr** [comment]
Should be fixed in https://github.com/xeffyr/termux-extra-packages/commit/82028ab93fbf4a6fc37778ec8180cece11600336
