### ISSUE TITLE
Unable to access https://termux.xeffyr.ml/ from China

### ISSUE THREAD

**Issue by zaoqi** [xeffyr/termux-extra-packages#30]
Please move it to github.io

**Comment by xeffyr** [comment]
@zaoqi Looks like you don't have access to cloudflare at all. I use it as DNS provider.

However all files are hosted over ipfs. Tell me if you can access link: https://ipfs.io/ipfs/QmcVkNr44enkWYBndidELhT52PB8B5jWrDZxiSoptyoxsi/

About github.io: moving ~1.5 GB of files to github.io will make repository updating too hard as i have to store everything in git.

**Comment by zaoqi** [comment]
I can't access ipfs.io

**Comment by xeffyr** [comment]
@zaoqi Ok, this link https://thunix.org/~xeffyr/termux-repo/, you can access ?

**Comment by zaoqi** [comment]
I can access

**Comment by xeffyr** [comment]
So, you need to use `https://thunix.org/%7Exeffyr/termux-repo/` instead of `termux.xeffyr.ml`.
