### ISSUE TITLE
Ask to add sdl2-dev

### ISSUE THREAD

**Issue by OldMcWeb** [xeffyr/termux-extra-packages#33]
I don't know if it fits in your repository but to compile sdl software it would be helpfull to have sdl-dev, libsdl-dev.

Thanks for your great work!
Flo

**Comment by xeffyr** [comment]
> it would be helpfull to have sdl-dev, libsdl-dev.

SDL v1.x is available.

> Ask to add sdl2-dev

SDL v2.x will be soon.

**Comment by xeffyr** [comment]
Package added, now you do ```pkg install libsdl2 libsdl2-dev``` to install it.
