### ISSUE TITLE
Package request: Emacs GUI

### ISSUE THREAD

**Issue by Linden6** [xeffyr/termux-extra-packages#34]
Although the terminal version of Emacs is available in the main Termux package repository, it would be useful to have the GUI version available so that graphics were supported within it.  (Most of the orgmode files that I work on contain thumbnail images that I can then click on to open in an image viewer.  It would be useful to be able to replicate this behaviour in Android.)

Thanks.

**Comment by xeffyr** [comment]
This issue was moved to termux/x11-packages#1
